name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        compiler: [cl, gcc, clang]
        include:

        exclude:
        - os: windows-latest
          compiler: gcc

        - os: ubuntu-latest
          compiler: cl
          

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: ilammy/msvc-dev-cmd@v1.10.0
      if: ${{ matrix.os }} == windows-latest
    
    - run: pip install meson ninja -r requirements.txt

    - if: ${{ matrix.compiler }} == gcc
      env:
        CC: ${{ matrix.compiler }}
        CXX: g++

    - name: build
      run: |
        meson --buildtype=debugoptimized bin
        ninja -C bin

    - name: run tests
      run: meson test -C bin --repeat 100 --print-errorlogs