name: build

on: [push, pull_request]

jobs:

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        cache: 'pip'
    
    - run: pip install meson ninja -r requirements.txt

    - uses: ilammy/msvc-dev-cmd@v1.10.0

    - run: meson bin
    - run: ninja -C bin
    - run: mmeson test -C bin --repeat 10  --print-errorlogs --wrap='valgrind -s'
    - run: mmeson test -C bin --repeat 10  --print-errorlogs --wrap='valgrind helgrind -s'

    - uses: actions/upload-artifact@v2
      with:
        name: windows-sandbox
        path: ./bin/sandbox.exe


  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        cache: 'pip'

    - run: pip install meson ninja -r requirements.txt

    - run: meson bin
      env:
        CC: gcc
    - run: ninja -C bin
    - run: mmeson test -C bin --repeat 10  --print-errorlogs --wrap='valgrind -s'
    - run: mmeson test -C bin --repeat 10  --print-errorlogs --wrap='valgrind helgrind -s'

    - uses: actions/upload-artifact@v2
      with:
        name: linux-sandbox
        path: ./bin/sandbox