name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: [gcc, clang]
        include:
          - os: windows-latest
            compiler: cl

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: ilammy/msvc-dev-cmd@v1.10.0
      if: ${{ matrix.os }} == windows-latest
    
    - run: pip install meson ninja -r requirements.txt

    - name: build
      env:
        cc: ${{ matrix.compiler }}
      run: |
        meson --buildtype=debugoptimized bin
        ninja -C bin

    - name: run tests
      run: meson test -C bin -t 10 --repeat 10 --print-errorlogs